project_id = "eoptlujvecbtorzrluoi"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-google-places]
    verify_jwt = true
  [functions.scrape-federation]
    verify_jwt = true
