UPDATE public.federations_sportives f SET site_web = m.new_url
FROM (VALUES
('https://www.ff-handball.org','https://www.ffhandball.fr'),
('https://ff-pelotebasque.fr','https://ffpb.net'),
('https://www.ffpolo.com','https://www.francepolo.com'),
('https://www.ffjbt.com','https://ffsport-tambourin.fr'),
('https://www.ffbap.fr','https://ballonaupoing.com'),
('https://www.ff-longuepaume.com','https://www.federation-longue-paume.fr'),
('https://www.ffpsa.fr','https://www.ffpsa.net'),
('https://www.ffmotonautique.com','https://www.ffmotonautique.fr'),
('https://www.ffjoute.com','https://www.ffjsn.fr'),
('https://www.ff-karate.fr','https://www.ffkarate.fr'),
('https://www.ffbaba.fr','https://fba-da.com'),
('https://www.ffkmda.fr','https://www.ffkmda.com'),
('https://www.ffaaa.fr','https://www.aikido.com.fr'),
('https://ffab.fr','https://www.ffabaikido.com/fr/'),
('https://ffwushu.fr','https://www.ffaemc.fr'),
('https://www.escrime-ffe.fr','https://www.ffescrime.fr'),
('https://www.ffl.fr','https://www.fflutte.com'),
('https://www.pentathlon.fr','https://www.ffpentathlon.fr'),
('https://www.ffst.fr','https://ffstmushing.org'),
('https://www.ffslc.org','https://ffslc.fr'),
('https://www.ffpulka.fr','https://ffptc.fr'),
('https://www.ffsg.org','https://www.ffsportsdeglace.fr'),
('https://www.ffgymnastique.fr','https://www.ffgym.fr'),
('https://www.ff-force.fr','https://www.ffforce.fr'),
('https://www.ffdtb.fr','https://fftwirl.fr'),
('https://www.doubledutchfrance.fr','https://www.doubledutch.fr'),
('https://www.ff-aero.fr','https://www.ffa-aero.fr'),
('https://www.ff-aerostation.org','https://ffaerostation.org'),
('https://www.ffvv.org','https://www.ffvp.fr'),
('https://ff-helico.fr','https://helico.org'),
('https://tir.ffti.fr','https://www.fftir.org'),
('https://www.ffbsq.org','https://ffbsq.fr'),
('https://www.ffballtrap.com','https://www.ffbt.asso.fr'),
('https://www.ffdf.org','https://www.ff-flyingdisc.fr'),
('https://www.ffcl.info','https://www.courselandaise.fr'),
('https://www.ffcv.org','https://ffcv.org'),
('https://www.ffpsc.fr','https://www.ffpspeches.fr'),
('https://www.ffsa.asso.fr','https://www.sportadapte.fr')
) AS m(old_url, new_url)
WHERE rtrim(f.site_web, '/') = m.old_url;