CREATE TABLE public.federations_sportives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nom text NOT NULL,
  sigle text,
  categorie text NOT NULL,
  site_web text NOT NULL,
  is_paralympique boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.federations_sportives TO anon, authenticated;
GRANT ALL ON public.federations_sportives TO service_role;

ALTER TABLE public.federations_sportives ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read federations_sportives" ON public.federations_sportives FOR SELECT USING (true);
CREATE INDEX idx_federations_categorie ON public.federations_sportives (categorie);

INSERT INTO public.federations_sportives (nom, sigle, categorie, site_web, is_paralympique) VALUES
('Football','FFF','Sports collectifs','https://www.fff.fr',false),
('Football américain','FFFA','Sports collectifs','https://www.fffa.org',false),
('Rugby','FFR','Sports collectifs','https://www.ffr.fr',false),
('Rugby à XIII','FFR13','Sports collectifs','https://www.ffr13.fr',false),
('Basketball','FFBB','Sports collectifs','https://www.ffbb.com',false),
('Handball','FFHB','Sports collectifs','https://www.ff-handball.org',false),
('Volley','FFVB','Sports collectifs','https://www.ffvolley.org',false),
('Hockey','FFH','Sports collectifs','https://www.ffhockey.org',false),
('Hockey sur glace','FFHG','Sports collectifs','https://www.hockeyfrance.com',false),
('Baseball, softball','FFBS','Sports collectifs','https://www.ffbs.fr',false),
('Pelote basque','FFPB','Sports collectifs','https://ff-pelotebasque.fr',false),
('Polo','FFP','Sports collectifs','https://www.ffpolo.com',false),
('Jeu de balle au tambourin','FFJBT','Sports collectifs','https://www.ffjbt.com',false),
('Ballon au poing','FFBAP','Sports collectifs','https://www.ffbap.fr',false),
('Tennis','FFT','Sports de raquette','https://www.fft.fr',false),
('Badminton','FFBAD','Sports de raquette','https://www.ffbad.org',false),
('Tennis de table','FFTT','Sports de raquette','https://www.fftt.com',false),
('Squash','FFSQUASH','Sports de raquette','https://www.ffsquash.com',false),
('Longue paume','FFLP','Sports de raquette','https://www.ff-longuepaume.com',false),
('Natation','FFN','Sports aquatiques','https://www.ffnatation.fr',false),
('Études et sports sous-marins','FFESSM','Sports aquatiques','https://ffessm.fr',false),
('Pêche sportive en apnée','FFPSA','Sports aquatiques','https://www.ffpsa.fr',false),
('Triathlon et disciplines enchaînées','FFTRI','Sports aquatiques','https://www.fftri.com',false),
('Voile','FFVOILE','Sports aquatiques','https://www.ffvoile.fr',false),
('Aviron','FFAVIRON','Sports aquatiques','https://www.ffaviron.fr',false),
('Canoë-kayak et sports de pagaie','FFCK','Sports aquatiques','https://www.ffck.org',false),
('Ski nautique et wakeboard','FFSNW','Sports aquatiques','https://ffsnw.fr',false),
('Surf','FFSURF','Sports aquatiques','https://www.surfingfrance.com',false),
('Motonautique','FFMN','Sports aquatiques','https://www.ffmotonautique.com',false),
('Joute et sauvetage nautique','FFJSN','Sports aquatiques','https://www.ffjoute.com',false),
('Sauvetage et secourisme','FFSS','Sports aquatiques','https://www.ffss.fr',false),
('Judo-jujitsu et disciplines associées','FFJDA','Arts martiaux & combat','https://www.ffjudo.com',false),
('Karaté et disciplines associées','FFKDA','Arts martiaux & combat','https://www.ff-karate.fr',false),
('Boxe et disciplines associées','FFB','Arts martiaux & combat','https://www.ffboxe.com',false),
('Boxe américaine et disciplines associées','FFBABA','Arts martiaux & combat','https://www.ffbaba.fr',false),
('Savate, boxe française et disciplines associées','FFSBFDA','Arts martiaux & combat','https://www.ffsavate.com',false),
('Kick boxing, muay thaï et disciplines associées','FFKMDA','Arts martiaux & combat','https://www.ffkmda.fr',false),
('Taekwondo et disciplines associées','FFTDA','Arts martiaux & combat','https://www.fftda.fr',false),
('Aïkido, aïkibudo, kinomichi et disciplines associées','FFAAA','Arts martiaux & combat','https://www.ffaaa.fr',false),
('Aïkido et de budo','FFAB','Arts martiaux & combat','https://ffab.fr',false),
('Arts énergétiques et arts martiaux chinois','FAEMC','Arts martiaux & combat','https://ffwushu.fr',false),
('Escrime','FFE','Arts martiaux & combat','https://www.escrime-ffe.fr',false),
('Lutte','FFL','Arts martiaux & combat','https://www.ffl.fr',false),
('Pentathlon moderne','FFPM','Arts martiaux & combat','https://www.pentathlon.fr',false),
('Athlétisme','FFA','Sports nature & montagne','https://www.athle.fr',false),
('Montagne et escalade','FFME','Sports nature & montagne','https://www.ffme.fr',false),
('Clubs alpins et de montagne','FFCAM','Sports nature & montagne','https://www.ffcam.fr',false),
('Spéléologie','FFS','Sports nature & montagne','https://ffspeleo.fr',false),
('Équitation','FFE','Sports nature & montagne','https://www.ffe.com',false),
('Cyclisme','FFC','Sports nature & montagne','https://www.ffc.fr',false),
('Cyclotourisme','FFVELO','Sports nature & montagne','https://www.ffvelo.fr',false),
('Golf','FFGOLF','Sports nature & montagne','https://www.ffgolf.org',false),
('Tir à l''arc','FFTA','Sports nature & montagne','https://www.ffta.fr',false),
('Course d''orientation','FFCO','Sports nature & montagne','https://www.ffcorientation.fr',false),
('Randonnée pédestre','FFRP','Sports nature & montagne','https://www.ffrandonnee.fr',false),
('Vol libre','FFVL','Sports nature & montagne','https://federation.ffvl.fr',false),
('Sports de traîneau, ski/VTT joëring et canicross','FFST','Sports nature & montagne','https://www.ffst.fr',false),
('Sports et loisirs canins','FFSLC','Sports nature & montagne','https://www.ffslc.org',false),
('Pulka et traîneau à chiens','FFPULKA','Sports nature & montagne','https://www.ffpulka.fr',false),
('Ski','FFS','Sports d''hiver & glisse','https://www.ffs.fr',false),
('Sports de glace','FFSG','Sports d''hiver & glisse','https://www.ffsg.org',false),
('Roller et skateboard','FFRS','Sports d''hiver & glisse','https://ffroller-skateboard.fr',false),
('Gymnastique','FFGYM','Fitness, danse & force','https://www.ffgymnastique.fr',false),
('Danse','FFDANSE','Fitness, danse & force','https://www.ffdanse.fr',false),
('Haltérophilie, musculation','FFHM','Fitness, danse & force','https://www.ffhaltero.fr',false),
('Force','FFFORCE','Fitness, danse & force','https://www.ff-force.fr',false),
('Twirling bâton','FFDTB','Fitness, danse & force','https://www.ffdtb.fr',false),
('Double dutch-jump rope','FDDJR','Fitness, danse & force','https://www.doubledutchfrance.fr',false),
('Sport automobile','FFSA','Sports mécaniques & aériens','https://www.ffsa.org',false),
('Motocyclisme','FFM','Sports mécaniques & aériens','https://www.ffmoto.org',false),
('Aéromodélisme','FFAM','Sports mécaniques & aériens','https://www.ffam.asso.fr',false),
('Aéronautique','FFA','Sports mécaniques & aériens','https://www.ff-aero.fr',false),
('Aérostation','FFAERO','Sports mécaniques & aériens','https://www.ff-aerostation.org',false),
('Parachutisme','FFP','Sports mécaniques & aériens','https://www.ffp.asso.fr',false),
('Planeur ultraléger motorisé','FFPLUM','Sports mécaniques & aériens','https://www.ffplum.fr',false),
('Vol en planeur','FFVV','Sports mécaniques & aériens','https://www.ffvv.org',false),
('Hélicoptère','FFHELICO','Sports mécaniques & aériens','https://ff-helico.fr',false),
('Voitures radio commandées','FFVRC','Sports mécaniques & aériens','https://www.ffvrc.fr',false),
('Tir','FFTIR','Sports de précision','https://tir.ffti.fr',false),
('Pétanque et jeu provençal','FFPJP','Sports de précision','https://www.ffpjp.org',false),
('Billard','FFB','Sports de précision','https://www.ffbillard.com',false),
('Bowling et sports de quilles','FFBSQ','Sports de précision','https://www.ffbsq.org',false),
('Ball-trap','FFBT','Sports de précision','https://www.ffballtrap.com',false),
('Javelot tir sur cible','FFJTC','Sports de précision','https://www.ffjavelot.fr',false),
('Échecs','FFE','Sports de précision','https://www.echecs.asso.fr',false),
('Sport boules','FFSB','Sports de précision','https://www.ffsb.fr',false),
('Flying disc','FFDF','Sports de précision','https://www.ffdf.org',false),
('Course camarguaise','FFCC','Sports traditionnels & régionaux','https://www.ffcc.info',false),
('Course landaise','FFCL','Sports traditionnels & régionaux','https://www.ffcl.info',false),
('Char à voile','FFCV','Sports traditionnels & régionaux','https://www.ffcv.org',false),
('Pêches sportives','FFPS','Pêche','https://www.ffpsc.fr',false),
('Handisport','FFH','Paralympiques','https://www.handisport.org',true),
('Sport adapté','FFSA','Paralympiques','https://www.ffsa.asso.fr',true);